# Generated by Django 3.2.7 on 2021-09-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='users/files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('directories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories_of_this', to='files.directory')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_of_this', to='files.file')),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
                'ordering': ('-created',),
            },
        ),
    ]
