# Generated by Django 3.2.7 on 2021-09-27 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directories_of_this', to='files.directory'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_of_this', to='files.file'),
        ),
    ]
