# Generated by Django 3.2.7 on 2021-09-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_set', to='files.directory'),
        ),
    ]
