# Generated by Django 3.2.7 on 2021-09-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
