# Generated by Django 3.2.7 on 2021-09-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_directory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
