# Generated by Django 3.2.7 on 2021-10-07 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
