# Generated by Django 3.2.7 on 2021-10-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
