# Generated by Django 3.2.7 on 2021-10-07 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='file',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
