# Generated by Django 3.2.7 on 2021-10-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20211007_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
    ]
