# Generated by Django 3.2.7 on 2021-10-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20211007_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories_of_this', to='files.directory'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='uuid_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_set', to='files.directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uuid_id',
            field=models.UUIDField(editable=False),
        ),
    ]
